update from https://www.facebook.com/syntezator/ 15.12.2020
RHVoice/Ukrainian pull request #1
Opened 2021-01-17 09:45 UTC by velmyshanovnyi

update from https://www.facebook.com/syntezator/ 15.12.2020

2021-01-17 23:07 UTC, velmyshanovnyi commented on userdict/src/dictionary.txt
> +оп+іку {і,й,та} піклування
дублювання
431
432
433

2021-01-31 22:54 UTC, alex19EP commented on userdict/src/dictionary.txt
> +оп+іку {і,й,та} піклування
can you fix it?

2021-01-31 22:57 UTC, alex19EP commented on userdict/src/dictionary.txt
> +оп+іку {і,й,та} піклування
on second glance. this a different words. I'm not sure what the problem is.

2021-01-31 23:09 UTC, alex19EP requested changes
since I don't know Ukrainian, I can only hope that everything is fine here.

2021-01-31 23:09 UTC, alex19EP commented on userdict/src/dictionary.txt
> +; 01 ; This dictionary for Ukrainian voices which are part of RHVoice Speech Synthesizer (https://github.com/RHVoice) contains the rules for the correct pronunciation of Ukrainian words and abbreviat
```suggestion
; 01 ; This dictionary for Ukrainian voices which are part of RHVoice Speech Synthesizer (https://github.com/RHVoice/RHVoice) contains the rules for the correct pronunciation of Ukrainian words and abbreviations.
```

I also don’t know why 01, 02, etc. are needed.

2021-02-01 04:45 UTC, velmyshanovnyi commented on userdict/src/dictionary.txt
> +; 01 ; This dictionary for Ukrainian voices which are part of RHVoice Speech Synthesizer (https://github.com/RHVoice) contains the rules for the correct pronunciation of Ukrainian words and abbreviat
Цифри  для того, чтоб сортировка по алфавиту работала, и ети строки оставались в нудному порядку сверху

2021-02-01 04:53 UTC, velmyshanovnyi commented on userdict/src/dictionary.txt
> +; 01 ; This dictionary for Ukrainian voices which are part of RHVoice Speech Synthesizer (https://github.com/RHVoice) contains the rules for the correct pronunciation of Ukrainian words and abbreviat
Пример: Документ правится например в блокноте, в конец документа добавляются новин правила. Потом сортируются по алфавиту, потом удаляются копии строк, потом комит на гитхаб

2021-02-01 07:43 UTC, alex19EP commented on userdict/src/dictionary.txt
> +; 01 ; This dictionary for Ukrainian voices which are part of RHVoice Speech Synthesizer (https://github.com/RHVoice) contains the rules for the correct pronunciation of Ukrainian words and abbreviat
now i understand. thanks.
when you address my suggestion i will merge this pr.

2021-03-17 10:57 UTC, VovaMobile commented on userdict/src/dictionary.txt
> +; 01 ; This dictionary for Ukrainian voices which are part of RHVoice Speech Synthesizer (https://github.com/RHVoice) contains the rules for the correct pronunciation of Ukrainian words and abbreviat
Hi developers,
I am official author of the Ukrainian pronunciation dictionary for Ukrainian voices of RHVoice speech synthesizer.
Today i commited latest official dictionary in new pull request.
First version of this dictionary included in the latest stable version of this synthesizer.
I continued developing, updating and improving this dictionary.
Official dictionary has only alphabet structure without digits and oder.

2021-04-19 12:23 UTC, closed without merging